In [4]:
import numpy as np
a = np.arange(3*3*3).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
print(a[1])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [6]:
print(a[1,2])

[15 16 17]


In [8]:
print(a[1,2,2])

17


In [9]:
print(a[-2,-2,-1])

14


In [12]:
names = np.array(["Qasim","Hamza", "Ali", "Junaid", "Humna", "Rashid"])
data = np.random.randn(6,4)
print(names, data, sep="\n")

['Qasim' 'Hamza' 'Ali' 'Junaid' 'Humna' 'Rashid']
[[-0.94384101 -0.34930866  0.72228494 -0.45623791]
 [-0.29182998  0.49730569 -1.27944646  0.03336064]
 [-0.57446007  0.09981321 -1.51259253  0.31092646]
 [-1.09512584  1.02170996  0.77455439  0.24676318]
 [ 1.09611021 -0.80345118 -1.76825138  0.14960786]
 [-2.77391955  1.2117087   0.68943757  0.0715176 ]]


In [13]:
names=="Qasim"

array([ True, False, False, False, False, False])

## FAncy slicing

In [14]:
a = np.arange(3*3*3).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [15]:
# a[slide,row,col


In [20]:
a = np.arange(3*3*3).reshape(3,3,3)
# print(a)
#slicing
print(a[[-1,-2,0],:,:])

[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]


In [26]:
print(a[:,1:,:])

[[[ 3  4  5]
  [ 6  7  8]]

 [[12 13 14]
  [15 16 17]]

 [[21 22 23]
  [24 25 26]]]


In [25]:
print(a[[-1,-2,0]])

[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]


In [27]:
a = np.arange(3*3*3).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [28]:
a[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [29]:
a[1] = 5 #whole values updated

In [30]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 5,  5,  5],
        [ 5,  5,  5],
        [ 5,  5,  5]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [31]:
names = np.array(["Qasim","Hamza", "Ali", "Junaid", "Humna", "Rashid"])
data = np.random.randn(6,4)
print(names, data, sep="\n")

['Qasim' 'Hamza' 'Ali' 'Junaid' 'Humna' 'Rashid']
[[-1.45334604  0.42324582  0.6671106  -0.94677475]
 [-0.29302137  1.1195305  -0.65570235  0.28321205]
 [-2.40265185  0.38457009 -1.4328803   0.18773289]
 [ 0.1398394  -0.33966679  0.1001048   1.41351982]
 [-0.96220006 -0.87372858 -0.35043866  1.65931721]
 [ 0.53259042 -1.13334119  1.64527483  1.14814201]]


In [32]:
names == "Hamza"

array([False,  True, False, False, False, False])

In [34]:
print(names[(names=='Qasim')|(names=='Hamza')])


['Qasim' 'Hamza']


In [35]:
print(data[(names=='Qasim')|(names=='Hamza')])

[[-1.45334604  0.42324582  0.6671106  -0.94677475]
 [-0.29302137  1.1195305  -0.65570235  0.28321205]]


In [38]:
print(data[~(names=='Qasim')|~(names=='Hamza')])
#or
print(data[(names!='Qasim')|(names!='Hamza')])

[[-1.45334604  0.42324582  0.6671106  -0.94677475]
 [-0.29302137  1.1195305  -0.65570235  0.28321205]
 [-2.40265185  0.38457009 -1.4328803   0.18773289]
 [ 0.1398394  -0.33966679  0.1001048   1.41351982]
 [-0.96220006 -0.87372858 -0.35043866  1.65931721]
 [ 0.53259042 -1.13334119  1.64527483  1.14814201]]
[[-1.45334604  0.42324582  0.6671106  -0.94677475]
 [-0.29302137  1.1195305  -0.65570235  0.28321205]
 [-2.40265185  0.38457009 -1.4328803   0.18773289]
 [ 0.1398394  -0.33966679  0.1001048   1.41351982]
 [-0.96220006 -0.87372858 -0.35043866  1.65931721]
 [ 0.53259042 -1.13334119  1.64527483  1.14814201]]


In [40]:
list(enumerate([8,7,4,3])) #enumerate generator function returns value and index

[(0, 8), (1, 7), (2, 4), (3, 3)]

In [43]:
a = np.arange(8*4).reshape(8,4)
for i, _ in enumerate(a):
    a[i] = i
    
a

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [47]:
a[-1::,:]

array([[7, 7, 7, 7]])

In [55]:
a[[5,4,3]]

array([[20, 21, 22, 23],
       [16, 17, 18, 19],
       [12, 13, 14, 15]])

In [53]:
a = np.arange(8*4).reshape(8,4)
print(a[[5,4,3],[3,0,1]])

[23 16 13]


## Transposing Arrays and swapping Axes

In [54]:
a = np.arange(8*4).reshape(8,4)
print(a)
print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]


In [56]:
print(a.transpose())

[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]


In [59]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a, b, sep='\n\n', end='\n\n')
#a@b to take dot product

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



In [60]:
a*b

array([[ 3,  8],
       [15, 24]])

In [61]:
a@b #dot product

array([[13, 16],
       [29, 36]])

In [62]:
a.dot(b)

array([[13, 16],
       [29, 36]])

In [63]:
a @ a.T

array([[ 5, 11],
       [11, 25]])

In [65]:
a = np.arange(3*3*3).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [67]:
a.T #transpose by default

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [69]:
print(a.transpose((2,1,0))) #custom transpose

[[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]


In [70]:
a = np.arange(12).reshape(4,3)
print(a) 
print(a.swapaxes(1,0)) 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [71]:
#transpose converts row to column and column to row
#swap values of the 2 axis

## 4.3 FAST FUNCTIONS