In [14]:
# % magic functions runs only on jupyter notebook
# %history
# %load tempfile.py (with proper filepath if file not in base location) - loads the the file in the current file
# %run temp.py runs the file and loads its result in the current file
%time sum([1,3,4]) # time taken to execute the function

Wall time: 0 ns


8

# PYTHON VS NUMPY

# PYTHON

In [15]:
%time l1 = list(range(1,3000000))

Wall time: 477 ms


In [16]:
%time [x+5 for x in l1][:10]

Wall time: 1.29 s


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [17]:
list(enumerate(['A','B','C']))

[(0, 'A'), (1, 'B'), (2, 'C')]

In [18]:
for i,v in list(enumerate(l1)):
    l1[i] = l1[i]+5

l1[:10]

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [19]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]

print("Before addding 5")
print(a)

for ri, rd in list(enumerate(a)):
    for ci,cd in list(enumerate(rd)):
        a[ri][ci] += 5
        
print("After addding 5")
print(a)


Before addding 5
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
After addding 5
[[6, 7, 8], [9, 10, 11], [12, 13, 14]]


# NUMPY

In [10]:
import numpy as np

In [20]:
%time l2 = np.arange(1,3000000)

Wall time: 26.8 ms


In [22]:

%time l2 + 5 #(not possible to add like this in simple python list, its called broadcasting performing plus operation)

Wall time: 23 ms


array([      6,       7,       8, ..., 3000002, 3000003, 3000004])

In [24]:
l2 = np.array([1,2,3])
print("Dimension:", l2.ndim)
print("Shape:", l2.shape)
print("Type:", l2.dtype)

Dimension: 1
Shape: (3,)
Type: int32


In [26]:
l2 = np.array([[1,2,3],
              [3,2,4]])
print("Dimension:", l2.ndim)
print("Shape:", l2.shape)
print("Type:", l2.dtype)

Dimension: 2
Shape: (2, 3)
Type: int32


In [30]:
l2 = np.random.randn(2,2) #gives 2x2 dimensional random array
print(l2)
print("Dimension:", l2.ndim)
print("Shape:", l2.shape)
print("Type:", l2.dtype)

[[-0.51074742  0.16733615]
 [ 0.39162656  0.24776419]]
Dimension: 2
Shape: (2, 2)
Type: float64


In [32]:
l2 = np.random.randn(2,2) #gives 2x2 dimensional random array
print(l2)
print("Dimension:", l2.ndim)
print("Shape:", l2.shape)
print("Type:", l2.dtype)
#l1[row,column]

[[-1.06824412 -0.06310736]
 [-1.69074458 -0.10726051]]
Dimension: 2
Shape: (2, 2)
Type: float64


In [34]:
l2 = np.arange(27).reshape(3,3,3) #gives 2x2 dimensional random array
print(l2)
print("Dimension:", l2.ndim)
print("Shape:", l2.shape)
print("Type:", l2.dtype)
#l2(slideNumber i, rowNumber j, columnNumber k)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dimension: 3
Shape: (3, 3, 3)
Type: int32


In [39]:
l2[1]
l2[1,2]
l2[1,2,1]

16

In [40]:
l2 = np.arange(27).reshape(3,3,3) #gives 2x2 dimensional random array
print(l2)
l2+5

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]],

       [[14, 15, 16],
        [17, 18, 19],
        [20, 21, 22]],

       [[23, 24, 25],
        [26, 27, 28],
        [29, 30, 31]]])

In [49]:
l3 = np.arange(50) #generate n dimensional array till given index (same as range in python)
l3 = np.arange(1,10, 2)
print(l3)

[1 3 5 7 9]


# A multidimensional array object

In [53]:
a = np.arange(1,11) # from 1 to 10
print(a)
print("Dimension:", a.ndim)
print("Shape:", a.shape)
print("Type:", a.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
Dimension: 1
Shape: (10,)
Type: int32


In [55]:
a = np.arange(1,26).reshape(5,5)
print(a)
print("Dimension:", a.ndim)
print("Shape:", a.shape)
print("Type:", a.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Dimension: 2
Shape: (5, 5)
Type: int32


In [57]:
a = np.arange(1,13).reshape((3,4))
a = np.arange(1,13).reshape((2,6))
a = np.arange(1,13).reshape((4,3))
a = np.arange(1,13).reshape((6,2))
print(a)
print("Dimension:", a.ndim)
print("Shape:", a.shape)
print("Type:", a.dtype)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Dimension: 2
Shape: (6, 2)
Type: int32


In [62]:
a = np.arange(1,28).reshape((3,3,3))
print(a)
print("Dimension:", a.ndim)
print("Shape:", a.shape)
print("Itemsize:", a.itemsize) #size in bits - normally 4 bits for int
print("Type:", a.dtype)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Dimension: 3
Shape: (3, 3, 3)
Itemsize: 4
Type: int32


In [63]:
a = np.random.randn(3,3,3,3)
print(a)
print("Dimension:", a.ndim)
print("Shape:", a.shape)
print("Itemsize:", a.itemsize) #size in bits - normally 4 bits for int
print("Type:", a.dtype)

[[[[ 1.24152486e+00 -1.95220291e+00 -1.58064236e+00]
   [ 2.78351232e-01  2.23493693e+00 -6.16144681e-01]
   [-4.75136945e-01  7.37213014e-01  8.53408140e-02]]

  [[-1.20726660e-01  5.32513797e-01 -1.17911465e+00]
   [ 1.23140599e+00  1.16425621e+00 -2.10684862e+00]
   [-3.23937980e-01 -3.53970340e-01  8.22342721e-01]]

  [[ 3.42746964e-01  9.63409138e-01 -3.06118845e-01]
   [ 7.73843818e-01  2.13511403e-01  7.46701061e-01]
   [ 1.93358450e-01 -1.42653995e+00 -9.17246778e-01]]]


 [[[-4.85441665e-01 -4.23649686e-01 -8.95736418e-02]
   [ 9.63840491e-01 -6.88374391e-01  9.50593286e-01]
   [-2.53386982e-01  5.39775559e-01 -1.40116043e+00]]

  [[-1.37072218e+00  2.96616620e-01 -4.18570377e-01]
   [-1.23823389e-01  9.93604772e-01 -7.85198225e-01]
   [-5.93079128e-01 -1.97872810e+00 -7.75582303e-01]]

  [[ 3.68978448e-01 -8.23297360e-01  9.20476454e-02]
   [ 8.07489726e-01 -1.58879422e+00 -8.20703518e-01]
   [ 1.82504202e-03  1.51173948e+00 -4.13232099e-01]]]


 [[[ 1.05694211e+00 -6.1806707

In [72]:
a = np.arange(1,26).reshape(5,5)
print(a)
print("Dimension:", a.ndim)
print("Shape:", a.shape)
print("Type:", a.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Dimension: 2
Shape: (5, 5)
Type: int32


In [73]:
a % 2 == 0

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [80]:
a = np.arange(1,28).reshape(3,3,3)
a*2
a+2
a/2
a**2 #power
a**0.5 #square root

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974],
        [2.64575131, 2.82842712, 3.        ]],

       [[3.16227766, 3.31662479, 3.46410162],
        [3.60555128, 3.74165739, 3.87298335],
        [4.        , 4.12310563, 4.24264069]],

       [[4.35889894, 4.47213595, 4.58257569],
        [4.69041576, 4.79583152, 4.89897949],
        [5.        , 5.09901951, 5.19615242]]])

# creating ndarrays

### np.array (copies the array)

In [88]:
# deep copy = new copy
# shallow copy = new reference

#this is deep copy
l = [1,2,3]
print(type(l))

<class 'list'>


In [86]:
a = np.array(l)
b = np.array(a)

print(a is b)
type(a)

False


numpy.ndarray

### np.asarray

In [96]:
# deep copy = new copy
# shallow copy = new reference

#this is shallow copy

# hat asarray does is
# 1 array -> shallow copy
# 2 array -> change dtype -> deep copy
# 3 if not array -> deep copy
l = [1,2,3]
print(type(l))

a = np.asarray(l)
b = np.asarray(a)
c = np.asarray(a, dtype=np.float64)

print(a is b) #2
print(l is a) #1
print(c is a) #3
type(a)

<class 'list'>
True
False
False


numpy.ndarray